name: Pytest
on: [push]

job:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up the python ${{ matrix.python-version}}
      uses: actions/setup-python-version@2
      with:
        python-version: ${{ matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt]; the pip install -r requirements.txt; fi
    - name: Test with pytest
      run : |
        pytest
        
